//
export const allProducts = [
    // Feature Products
   
      {
        id: 1,
        name: "Galaxy Explorer Hoodie",
        brand: "Nike",
        description: "A sleek hoodie designed for space enthusiasts.",
        price: 500,
        image: "../../../images/products/f1.jpg",
        category: "feature",
        quantity: 1,
        size: null,
        star: 5,
      },
      {
        id: 2,
        name: "Lunar Landing Sneakers",
        brand: "Puma",
        description: "Comfortable sneakers inspired by lunar missions.",
        price: 600,
        image: "../../../images/products/f2.jpg",
        category: "feature",
        quantity: 1,
        size: null,
        star: 4,
      },
      {
        id: 3,
        name: "Cosmic Vibes T-Shirt",
        brand: "Under Armour",
        description: "Feel the cosmic vibes with this stylish tee.",
        price: 450,
        image: "../../../images/products/f3.jpg",
        category: "feature",
        quantity: 1,
        size: null,
        star: 3,
      },
      {
        id: 4,
        name: "Orbit Racer Jacket",
        brand: "Reebok",
        description: "A lightweight jacket perfect for cool weather.",
        price: 1000,
        image: "../../../images/products/f4.jpg",
        category: "feature",
        quantity: 1,
        size: null,
        star: 4,
      },
      {
        id: 5,
        name: "Meteor Trail Shorts",
        brand: "New Balance",
        description: "Durable shorts for your outdoor adventures.",
        price: 800,
        image: "../../../images/products/f5.jpg",
        category: "feature",
        quantity: 1,
        size: null,
        star: 3,
      },
      {
        id: 6,
        name: "Nebula Graphic Tee",
        brand: "ASICS",
        description: "A bold T-shirt featuring a nebula graphic.",
        price: 650,
        image: "../../../images/products/f6.jpg",
        category: "feature",
        quantity: 1,
        size: null,
        star: 4,
      },
      {
        id: 7,
        name: "Astro Expedition Cap",
        brand: "Fila",
        description: "Keep cool with this breathable expedition cap.",
        price: 1200,
        image: "../../../images/products/f7.jpg",
        category: "feature",
        quantity: 1,
        size: null,
        star: 5,
      },
      {
        id: 8,
        name: "Stellar Sports Backpack",
        brand: "Columbia",
        description: "A spacious backpack for all your gear.",
        price: 999,
        image: "../../../images/products/f8.jpg",
        category: "feature",
        quantity: 1,
        size: null,
        star: 4,
      },
    
  
    // New Arrival Products
    
      {
        id: 9,
        name: "Galaxy Voyager Jacket",
        brand: "Adidas",
        description: "A premium jacket designed for intergalactic adventures.",
        price: 899,
        image: "../../../images/products/n1.jpg",
        category: "newArrival",
        quantity: 1,
        size: null,
        star: 5,
      },
      {
        id: 10,
        name: "Solar Flare Sneakers",
        brand: "Nike",
        description: "High-performance sneakers built for cosmic athletes.",
        price: 245,
        image: "../../../images/products/n2.jpg",
        category: "newArrival",
        quantity: 1,
        size: null,
        star: 4,
      },
      {
        id: 11,
        name: "Nebula Glow Hoodie",
        brand: "Reebok",
        description: "Stay warm and stylish with this glow-in-the-dark hoodie.",
        price: 765,
        image: "../../../images/products/n3.jpg",
        category: "newArrival",
        quantity: 1,
        size: null,
        star: 3,
      },
      {
        id: 12,
        name: "Astral Expedition Pants",
        brand: "Under Armour",
        description: "Durable pants for outdoor explorations in any weather.",
        price: 890,
        image: "../../../images/products/n4.jpg",
        category: "newArrival",
        quantity: 1,
        size: null,
        star: 4,
      },
      {
        id: 13,
        name: "Meteor Impact Shoes",
        brand: "Puma",
        description: "Comfortable sneakers designed for the modern explorer.",
        price: 760,
        image: "../../../images/products/n5.jpg",
        category: "newArrival",
        quantity: 1,
        size: null,
        star: 5,
      },
      {
        id: 14,
        name: "Lunar Pulse T-Shirt",
        brand: "Fila",
        description:
          "A T-shirt that brings the power of the moon to your wardrobe.",
        price: 550,
        image: "../../../images/products/n6.jpg",
        category: "newArrival",
        quantity: 1,
        size: null,
        star: 3,
      },
      {
        id: 15,
        name: "Stellar Expedition Cap",
        brand: "New Balance",
        description: "A breathable cap designed for high-altitude expeditions.",
        price: 350,
        image: "../../../images/products/n7.jpg",
        category: "newArrival",
        quantity: 1,
        size: null,
        star: 4,
      },
      {
        id: 16,
        name: "Cosmic Explorer Backpack",
        brand: "Columbia",
        description: "A spacious and durable backpack for all your gear.",
        price: 640,
        image: "../../../images/products/n8.jpg",
        category: "newArrival",
        quantity: 1,
        size: null,
        star: 5,
      },
  
  ];
  